# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171001_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
