# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.TextField(default='', max_length=100),
        ),
    ]
