# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20171001_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
