# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='patient_name_title',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.AddField(
            model_name='profile',
            name='Religion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='Status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='blood_group_abo',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('O', 'O')], default='O', max_length=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='blood_group_rh',
            field=models.CharField(choices=[('P', '+'), ('M', '-')], default='P', max_length=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='congenital_disease',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='emergency_addr',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='emergency_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='profile',
            name='father_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('MEN', 'ชาย'), ('WOMEN', 'หญิง'), ('OTHER', 'อื่นๆ')], default='MAN', max_length=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_card_number',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AddField(
            model_name='profile',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='nationallity',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='occupy',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='pateint_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='patient_img',
            field=models.ImageField(default='picture/none/no-img.jpg', upload_to='picture/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='patient_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='patient_surname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='race',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='telphone_number',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
