# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20171001_2156'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
